# Generated by Django 3.1.7 on 2021-03-09 13:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taskmanager_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rejectedtask',
            unique_together={('task', 'assignee')},
        ),
    ]
