# Generated by Django 3.1.7 on 2021-03-10 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taskmanager_api', '0002_auto_20210309_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskAssignees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('reason', models.CharField(blank=True, max_length=200, null=True)),
                ('is_rejected', models.BooleanField(default=False)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='assignee',
        ),
        migrations.DeleteModel(
            name='RejectedTask',
        ),
        migrations.AddField(
            model_name='taskassignees',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_assignee', to='taskmanager_api.task'),
        ),
        migrations.AlterUniqueTogether(
            name='taskassignees',
            unique_together={('task', 'assignee')},
        ),
    ]
