# Generated by Django 3.1.7 on 2021-03-11 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager_api', '0003_auto_20210310_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='request_status',
        ),
        migrations.RemoveField(
            model_name='taskassignees',
            name='is_rejected',
        ),
        migrations.AddField(
            model_name='task',
            name='task_status',
            field=models.CharField(choices=[('UNASSIGNED', 'UNASSIGNED'), ('PENDING', 'PENDING'), ('ACCEPTED', 'ACCEPTED'), ('REJECTED', 'REJECTED')], default='UNASSIGNED', max_length=10),
        ),
        migrations.AddField(
            model_name='taskassignees',
            name='request_status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('ACCEPT', 'ACCEPT'), ('REJECT', 'REJECT')], default='PENDING', max_length=7),
        ),
    ]
